feat: webhook module v1
across-protocol/indexer pull request #101
Opened 2024-11-14 18:30 UTC by daywiss

# Motivation
We want to be able to handle webhook requests to the indexer, starting with deposit status

# changes
This adds a module in the indexer to startup an express based webhook manager, with an interface to add new event types, as well as register many webhooks. 

# usage
`factory` in the main entry point which gives you a  `WebhookFactory` call, which returns `{webooks ,express ,notifier}`.  As the indexer, all you need to do is call webhooks.write({type:'DepositStatus',event:EventData})
You also need to setup an interval to run the notification worker by calling `notifier.tick()` which will try to send out all pending notifications to webhooks

integrators will call into the express app on `POST /webhook`, passing body = `{type:'DepositStatus',filter:{originChainId,depositTxHash}, url:string}`. This will begin the listening process for indexer updates. It should also emit a first deposit status if one exists.

# testing
this has not been tested

2024-11-14 18:47 UTC, daywiss commented on packages/indexer/src/webhooks/notifier.ts
> +          );
this is where the webhook callback happens. further down you can see we try a backoff strategy if it fails

2024-11-14 18:49 UTC, daywiss commented on packages/indexer/src/webhooks/webhook.ts
> +export class DepositStatusWebhook implements IWebhook {
this is the specific deposit status processor we care about, its wrapped in a higher level webhooks class in case we want to define different types

2024-11-14 18:51 UTC, daywiss commented on packages/indexer/src/webhooks/factory.ts
> +export function WebhookFactory(config: Config, deps: Dependencies) {
main entry point as an indexer

2024-11-14 18:51 UTC, daywiss commented on packages/indexer/src/webhooks/factory.ts
> +        );
this is where we instance and register each webhook event type, currently we only have 'DepositStatus'
we can see it has a callback `notify` which queues it in the notifier, which persists notification state

2024-11-14 18:52 UTC, daywiss commented on packages/indexer/src/webhooks/notifier.ts
> +  public tick = async (now = Date.now()): Promise<void> => {
you will manually need to call notifier.tick on an interval somewhere in indexer code ( or whoever consumes this module)

2024-11-14 18:52 UTC, daywiss commented on packages/indexer/src/webhooks/notifier.ts
> +    super({ ...deps, notify: post });
makes a specific webhook caller, we could theoretically pass in an event emitter for testing rather than https post

2024-11-14 18:53 UTC, daywiss commented on packages/indexer/src/webhooks/store.ts
> +export interface AsyncStore<V> {
abstract store, hopefully it wouldnt be too difficult to hook this up to postgres. will speed up development to have a common store interface

2024-11-14 18:53 UTC, daywiss commented on packages/indexer/src/webhooks/store.ts
> +export class RedisStore<V> implements AsyncStore<V> {
redis store if we want to use it

2024-11-14 18:54 UTC, daywiss commented on packages/indexer/src/webhooks/utils.ts
> +export async function post(url: string, data: any): Promise<void> {
what we use to post to webhook

2024-11-14 18:55 UTC, daywiss commented on packages/indexer/src/webhooks/webhooks.ts
> +      }
this was my attempt at gaurding a webhook for a domain, but this may need to be tested/rethought

2024-11-14 18:58 UTC, daywiss commented on packages/indexer/src/webhooks/express.ts
> +    "/webhook",
integrator register a new webhook

2024-11-18 12:04 UTC, amateima requested changes
Looks good. Left a few comments.

2024-11-18 17:38 UTC, daywiss commented on packages/webhooks/src/router.ts
> +export function WebhookRouter(deps: Dependencies): express.Router {
>following our conversation on Friday, the best for now would be to remove the express logic from the webhooks package and declare a /webhooks/register endpoint in the indexer API that (1) saves the webhook request in the DB

This logic has been updated to remove references to express app, and only return a router, which is very portable.  The reason i think we should at least return a router, is because there needs to be type validation on the routes, and you dont want the consumer of the webhook library to need to know the types the library expects to correctly validate.

> P.S I asked Matt if the initial status should be sent to the webhook request URL or if we can attach it to the response body of the /register endpoint. But must likely it will be option (1)

would highly prefer all data updates go through webhook calls. it simplifies both our logic and consumer logic.

2024-11-18 17:44 UTC, daywiss commented on packages/webhooks/src/types.ts
> +  event: JSONValue;
ive renamed this to "data"

2024-11-18 17:45 UTC, daywiss commented on packages/webhooks/src/notifier.ts
> +    this.completed = deps.completed;
removed any stateful notifications

2024-11-18 17:45 UTC, daywiss commented on packages/webhooks/src/types.ts
> +}
renamed this

2024-11-18 19:27 UTC, james-a-morris commented on packages/webhooks/src/database/webhookClientRepository.ts
> +  }
```suggestion
  public unregisterClient(clientId: string): Promise<void> {
    if (!(await this.store.has(clientId))) {
      throw new Error(`Client with id ${clientId} does not exist.`);
    }
    return this.store.delete(clientId);
  }
```

2024-11-18 19:27 UTC, james-a-morris commented on packages/webhooks/src/database/webhookClientRepository.ts
> +  public async getClient(clientId: string): Promise<WebhookClient | undefined> {
```suggestion
  public getClient(clientId: string): WebhookClient | undefined {
```

2024-11-18 19:27 UTC, james-a-morris commented on packages/webhooks/src/database/webhookClientRepository.ts
a lot of these functions may not need to be async

2024-11-18 19:27 UTC, james-a-morris commented on packages/webhooks/src/store.ts
> +  async *entries(): AsyncIterableIterator<[string, V]> {
OOC what is this *entries invocation?

2024-11-19 17:24 UTC, daywiss commented on packages/webhooks/src/database/webhookClientRepository.ts
> +  }
these need async, the stores are async cuz they will be calling a database

2024-11-19 17:25 UTC, daywiss commented on packages/webhooks/src/database/webhookClientRepository.ts
the store functions are all async, even though right now they are using a memory map, eventually will plugin a real database

2024-11-19 22:59 UTC, amateima approved these changes

2024-11-20 09:42 UTC, merged