feat(webhooks): add postgres persistence to clients and requests
across-protocol/indexer pull request #108
Opened 2024-11-20 18:50 UTC by daywiss

# motivation
We need to store client and webhook url data

# changes
This adds persistence through postgres and typeorm entities. Removed the store concept for a direct connection to typeorm for simplicity, since we dont expect to use other stores.

2024-11-20 22:49 UTC, james-a-morris commented on packages/webhooks/package.json
> +    "superstruct": "2.0.3-1",
Ooc is this a beta version?

2024-11-20 22:49 UTC, james-a-morris commented on packages/indexer-database/src/entities/WebhookClient.ts
> +  domains: string[];
Are these callback URIs?

2024-11-20 22:58 UTC, melisaguevara reviewed
looks good! Just two small comments
(Will approve when the migration files are included)

2024-11-20 22:58 UTC, melisaguevara commented on packages/webhooks/src/database/webhookClientRepository.ts
> +import { DataSource } from "typeorm";
We can also import this from "@repo/indexer-database". I mention this only in case this is the only reason we are including typeorm in this package.

2024-11-20 22:58 UTC, melisaguevara commented on packages/webhooks/src/factory.ts
> +import { entities } from "@repo/indexer-database";
Can we delete this import?

2024-11-20 22:59 UTC, melisaguevara commented on packages/webhooks/package.json
> +    "superstruct": "2.0.3-1",
Yes, their last official releas has some import/export errors.

2024-11-21 14:11 UTC, daywiss commented on packages/webhooks/src/database/webhookClientRepository.ts
> +import { DataSource } from "typeorm";
removed typeorm and any references

2024-11-21 15:02 UTC, melisaguevara approved these changes
lgtm!

2024-11-21 17:17 UTC, amateima requested changes

2024-11-21 17:17 UTC, amateima commented on packages/webhooks/src/eventProcessors/depositStatus.ts
> +  static type = "DepositStatus";
hardcoded strings should really be avoided. If this is common to all event processors, should we add the `type` field tot the IEventProcessor interface?
And also making it to have the `WebhookTypes` type

2024-11-21 17:26 UTC, melisaguevara commented on packages/indexer-database/src/migrations/1732198003042-Webhook.ts
> +    await queryRunner.query(
Just OOC, why should they be removed? Curious if there's anything we have to fix in the entities

2024-11-22 16:26 UTC, daywiss commented on packages/indexer-database/src/entities/WebhookClient.ts
> +export class WebhookClient {
this complicates things, but i can make it optional. right now we allow no client if configured that way

2024-11-26 11:47 UTC, amateima approved these changes

2024-11-26 12:22 UTC, merged