feat(errors): add error class and functions
across-protocol/indexer pull request #113
Opened 2024-11-22 20:19 UTC by james-a-morris

Initial PR to integrate a uniform data payload in the API

2024-11-22 21:48 UTC, amateima requested changes
Don't forget to add the package to the Dockerfile

2024-11-22 21:48 UTC, amateima commented on packages/error-handling/src/errors/AssertError.ts
> +    super(AssertError.name, message);
does this mean that the HTTP response body will be 
```
{
  error: "AssertError",
  message: message
}
```
?

2024-11-22 21:48 UTC, amateima commented on packages/error-handling/src/errors/IndexerHTTPError.ts
> +    private readonly httpStatusCode: StatusCodes,
should we make this optional and set a default code? 400 or 500

2024-11-22 21:48 UTC, amateima commented on packages/error-handling/src/errors/IndexerHTTPError.ts
> +import { StatusCodes } from "http-status-codes";
maybe we should export these too so that the indexer-api would not have to install this package

2024-11-22 21:48 UTC, amateima commented on packages/error-handling/src/index.ts
> +export * as utils from "./utils";
let's put all the exports in a single place
```suggestion
export * from "./utils";
```

2024-11-25 16:11 UTC, daywiss approved these changes

2024-11-25 18:13 UTC, james-a-morris commented on packages/error-handling/src/errors/IndexerHTTPError.ts
> +import { StatusCodes } from "http-status-codes";
https://github.com/across-protocol/indexer/pull/113/commits/a8d11c18598a6a8ab2fdba866f3f30f205ba9e3a

2024-11-25 18:13 UTC, james-a-morris commented on packages/error-handling/src/errors/IndexerHTTPError.ts
> +    private readonly httpStatusCode: StatusCodes,
I think it should be intentional otherwise we'd want to use `IndexerError`

2024-11-25 18:15 UTC, james-a-morris commented on packages/error-handling/src/errors/IndexerError.ts
> +export abstract class IndexerError extends Error {
Quite possibly - I will leave it to @alexandrumatei36

2024-11-25 19:44 UTC, amateima commented on packages/error-handling/src/errors/IndexerError.ts
> +export abstract class IndexerError extends Error {
@james-a-morris we can do a quick renaming. I agree with David that we should design these packages as they would be used in the future in other repos/apps too

2024-11-25 19:45 UTC, amateima approved these changes
This is great work! It can be merged after renaming the error class

2024-11-25 19:46 UTC, james-a-morris commented on packages/error-handling/src/errors/IndexerError.ts
> +export abstract class IndexerError extends Error {
I'd prefer to avoid naming it just `Error` when dropping the `Indexer`. How about `FormattedError`?

2024-11-25 20:42 UTC, james-a-morris commented
> This is great work! It can be merged after renaming the error class

resolved offline - we'll follow in post

2024-11-25 20:42 UTC, merged