feat: add basic indexer api
across-protocol/indexer pull request #12
Opened 2024-08-15 17:09 UTC by daywiss

# motivation
stub out pontential api calls

# changes
added some basic calls for mvp as well as potential future calls

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/package.json
> +    "superstruct": "2.0.3-1",
ooc what is `2.0.3-1`? Is this a beta build

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/main.ts
> +import { type Router } from "express";
I'm not sure I've seen this syntax before - is this importing the router as a `type`?

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/main.ts
> +  env: Record<string, string | undefined>,
If we're including superstruct does it make sense to do this parsing prior to entering the `Main` function and exporting a superstruct type?

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/main.ts
> +  env: Record<string, string | undefined>,
This a more long term item but it could be useful to start reasoning about it now

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/main.ts
> +  if (postgres) {
If postgres fails - would we want to throw?

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/services/indexer.ts
> +type APIHandler = (
Is this generic? Can we place it in a common types directory?

2024-08-20 14:41 UTC, james-a-morris commented on packages/indexer-api/src/services/indexer.ts
> +        next(err);
OOC what is the purpose of calling `next` directly? Is this so that we capture the error to a specific error handler?

2024-08-20 16:11 UTC, daywiss commented on packages/indexer-api/package.json
> +    "superstruct": "2.0.3-1",
dont know, i think its just matching the version we had used elsewhere

2024-08-20 16:12 UTC, daywiss commented on packages/indexer-api/src/main.ts
> +import { type Router } from "express";
yes its a way you can specify you are only importing the type per variable

2024-08-20 16:14 UTC, melisaguevara commented on packages/indexer-api/package.json
> +    "superstruct": "2.0.3-1",
Yes, I mentioned it in a previous PR.
It is [this pre-release version](https://github.com/ianstormtaylor/superstruct/releases/tag/v2.0.3-1) that fixes superstruct exports. I was having importing issues with latest.

2024-08-20 16:16 UTC, daywiss commented on packages/indexer-api/src/main.ts
> +  env: Record<string, string | undefined>,
yes its possible, id probably suggest exporting a single envToConfig function which takes an env and produces and validates the config. and that gets passed into the library from the node/app

2024-08-20 16:18 UTC, daywiss commented on packages/indexer-api/src/main.ts
> +  if (postgres) {
it will throw on `connectToDatabase` a few lines up.  this is just so postgres can be optional, in case you are not running an api that needs it

2024-08-20 16:19 UTC, daywiss commented on packages/indexer-api/src/services/indexer.ts
> +type APIHandler = (
not sure it should be enshrined yet, was just trying it as a general interface to api calls, there are some drawbacks to it since you have to cast your return types to json, and you have to validate your input parameters, but might not be a way around this

2024-08-20 16:20 UTC, daywiss commented on packages/indexer-api/src/services/indexer.ts
> +  async function deposits(queryParams: JSON) {
can you suggest a quick way to do that?

2024-08-20 16:21 UTC, daywiss commented on packages/indexer-api/src/services/indexer.ts
> +        next(err);
you dont want to throw in an express handler, that will crash the app, passing this to next lets a successive handler deal with it, and in this case if you look at the express file, theres an error handler at the end which will parse and return it to the caller

2024-08-20 18:51 UTC, melisaguevara commented on packages/indexer-api/src/services/indexer.ts
> +    }
We don't have this in the Deposit entity but I imagine we would like to have it.
@james-a-morris do you know where should we get the integrator from?

2024-08-20 18:53 UTC, melisaguevara approved these changes
LGTM!

2024-08-20 20:32 UTC, amateima requested changes

2024-08-20 20:32 UTC, amateima commented on packages/indexer-api/src/services/indexer.ts
> +export function Indexer(db: DataSource): Record<string, APIHandler> {
It is not very easy to tell what this function does only by looking at its name. Also, putting all the endpoints handlers in a single function creates a huge function that is not very easy to read.

2024-08-20 20:32 UTC, amateima commented on packages/indexer-api/src/services/indexer.ts
> +  });
Maybe this type of Data Transfer Object (url params, query parameters, request body, etc) should have their own place and since this is something related to the REST API, my feeling is that this should be part of the `entrypoint` component I mentioned above

2024-08-20 20:32 UTC, amateima commented on packages/indexer-api/src/services/indexer.ts
> +  }
I think this is the only piece of code (the endpoint handler) that should stay here in the service file. Declaring endpoints, query parameters, url parameters, etc should be put in a single place from where the service will be called

2024-08-20 20:32 UTC, amateima commented on packages/indexer-api/src/services/indexer.ts
> +    }
We need the transaction call data to extract the integrator. Not sure if there is smth useful in the SDK that we can use

2024-08-20 20:32 UTC, amateima commented on packages/indexer-api/src/services/indexer.ts
> +    async (req: Request, res: Response, next: NextFunction) => {
Since this API will be exposed and promoted publicly, I think we should go for a more "RESTful" and declarative way of specifying endpoints, instead of this procedure call style.
Also it's easier to read the code if we mention explicitly the available endpoints: "deposit", "deposits", etc

2024-08-21 22:07 UTC, james-a-morris reviewed
can we include some form of swagger endpoint? AFAICT it should be decorators

2024-08-22 09:16 UTC, amateima commented
> can we include some form of swagger endpoint? AFAICT it should be decorators

I think swagger documentation is out of the scope of this PR, at least for now. It's possible that some of these endpoints will be documented on the docs.across.to website, so in this case a potential swagger UI will be used mostly internally

2024-08-23 14:22 UTC, daywiss commented
@amateima @james-a-morris Have several follow on prs to this which will address many of these comments, would like to get this in to no block new work for now

2024-08-23 18:34 UTC, amateima approved these changes

2024-08-26 13:05 UTC, merged