improve(indexer): add block timestamp to depositevent data
across-protocol/indexer pull request #129
Opened 2024-12-05 18:47 UTC by daywiss

# motivation
We want to store block timestamps with deposit data in order to calculate some metrics

# changes
This adds a column "blockTimestamp" to v3FundsDeposited, and queries per block range all the block timestamps and adds it to the data when storing in database

# profiling
We will use this new value and the existing "createdAt" value, which is our insertion time, for instance:
`const depositWriteTime = toSeconds(deposit.createdAt) - deposit.blockTimestamp`

2024-12-05 18:49 UTC, james-a-morris commented on packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
> +  blockTimestamp?: number;
Is this something we will eventually backfill? Could be a good candidate to make required with the prod backfilling

2024-12-05 20:02 UTC, melisaguevara commented on packages/indexer/src/database/SpokePoolRepository.ts
> +        blockTimestamp: blockTimes[event.blockNumber],
What do you think about considering quoteTimestamp as deposit date? I know there might be a tiny difference with the actual block number though.

2024-12-06 11:09 UTC, amateima requested changes

2024-12-06 11:09 UTC, amateima commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +  ): Promise<Record<number, number>> {
I think there's room for optimisation here. Instead of passing the whole block range, we can pass here a list with only the blocks we got deposit events for. 
This will avoid fetching thousands of blocks with no events during backfilling

2024-12-06 11:09 UTC, amateima commented on packages/indexer/src/database/SpokePoolRepository.ts
> +        blockTimestamp: blockTimes[event.blockNumber],
I think the most accurate will be to track the time when the user's tx got mined

2024-12-06 15:51 UTC, daywiss commented on packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
> +  blockTimestamp?: number;
im not totally sure how this works by making it required, i wanted to avoid having to rerun indexing to get this data, and allow it optionally going forward

2024-12-06 16:00 UTC, daywiss commented
@amateima I made 2 changes:
1. optimized the block timestamp query to only care about blocks where we have deposit events
2. log out the time difference directly after saving, so we can use datadog immediately

2024-12-07 12:25 UTC, amateima approved these changes

2024-12-16 16:24 UTC, merged