feat(indexer): add coingecko price collection from tokens against usd
across-protocol/indexer pull request #138
Opened 2024-12-18 19:51 UTC by daywiss

# motivation
we want to start collecting price data in the indexer

# changes
This adds an entity for historic prices, and a price processor in the indexer that runs every minute. it only stores a price once every 24 hours. Env can be configed based on coingecko price symbols.

2024-12-19 10:12 UTC, amateima requested changes

2024-12-19 10:12 UTC, amateima commented on packages/indexer/src/parseEnv.ts
> +  const coingeckoSymbols = parseArray(env.COINGECKO_SYMBOLS).map((symbol) =>
We should document this ENV value in the README and specify the format of it (list, object, etc)

2024-12-19 14:12 UTC, daywiss commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  date: string;
i think the complexity is that we only care about 1 price per day, which means deterministically calculating the "day" based on a js Date or timestamp becomes more involved. Ill add the logic and u can see if thats what you want

2024-12-19 14:13 UTC, daywiss commented on packages/indexer/src/services/priceProcessor.ts
> +          baseCurrency: symbol,
this is currently an enum, so if anything is wrong we can fix it in the enum

2024-12-19 14:28 UTC, daywiss commented on packages/indexer-database/packages/indexer-database/src/migrations/1733941169940-HistoricPrice.ts
> +}
yea this was a mistake. wil fix

2024-12-30 13:55 UTC, amateima requested changes

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> + */
These comments should be updated or removed

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +  public worker: Worker;
Is this property needed to be public?

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +    );
Would make sense to make the repository variables to be class properties and set them in the constructor? This way we would reduce the scope of `run()` function by not having it to deal with instantiating dependencies

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +    );
I see that `findTokenByAddress()` function works on a list of tokens that filters out the tokens for which we don't have the CoinGecko symbol defined in the indexer. I don't think this is necessary. 
The only condition we need to check is if the token is part of the supported tokens specified in the `@across-protocol/constants`. If we do this, we also don't need the CoinGecko env anymore

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +    const baseTokenInfo = findTokenByAddress(
We need to fetch price for input token too

2024-12-30 13:55 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +export class PriceWorker {
The way errors are handled in this worker should be reviewed and changed accordingly. The only situation in which the message should be discarded and execution should stop is the case when the deposit with a particular `depositId` and `originChainId` doesn't exist. Otherwise, we should log the error (as we do) **and** throw an error, so that the worker retries the message

2024-12-30 19:01 UTC, daywiss commented on packages/error-handling/src/utils/assert.ts
> +    return assertModule.ok(value !== null && value !== undefined, message);
i probably dont need to do this

2025-01-03 13:35 UTC, amateima requested changes
I haven't looked at the code yet. I tried to test it locally, but I hit this error
<img width="674" alt="Screenshot 2025-01-03 at 15 34 19" src="https://github.com/user-attachments/assets/ce56d0fb-9570-4cfe-b474-92587e2cf598" />

2025-01-06 11:35 UTC, amateima requested changes
I am not able to run the workers successfully, see screenshot for error.

<img width="677" alt="Screenshot 2025-01-06 at 13 29 49" src="https://github.com/user-attachments/assets/a8c83faf-77cc-4734-bc6c-3a68c614b5c2" />

I think the problem is at line 154 in the worker:

```
const deposit = await this.depositRepository.findOne({
      where: { depositId, originChainId },
    });
```

Is very possible for fill events to be fetched before the deposit events on the origin chain, so maybe in this case we should retry messages until the corresponding deposit event is found in the DB?

2025-01-07 16:10 UTC, james-a-morris requested changes
Could be worth reviewing: https://github.com/across-protocol/sdk/tree/master/src/coingecko

We could probably leverage this heavily to avoid code duplication. This will be helpful when we have to worry about SVM.

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  @Column({ type: "decimal" })
Is decimal needed here? Could a float be enough?

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  quoteCurrency: string;
Could be worth enumerated the expected values of these. We're unlikely to deviate from `usd` or `eth` or `azero` or `matic` as a base currency and the quote currency is unlikely to not be `usd`

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer-database/src/entities/RelayHashInfo.ts
> +  outputPriceUsd: number;
If we're willing to use `decimal` in the historic price, should we continue using it here?

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/package.json
> +    "luxon": "^3.5.0",
Do we need luxon for this? I think we could probably use the standard date types

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +      IndexerQueues.PriceQuery, // Use queue name as job name
OOC why do we repeat this parameter twice?

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +    await this.publishNewRelays(events.filledV3RelayEvents);
Could this (and the two async calls above it) be parallelized?

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/messaging/priceWorker.ts
> +    if (cachedPrice) return Number(cachedPrice.price);
nit: w/out the braces it's not immediately obvious that this isn't a one-liner but rather a conditional + a return
```suggestion
    if (cachedPrice) { 
        return Number(cachedPrice.price);
    }
```

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/messaging/priceWorker.ts
> +      normalizedInputAmount - normalizedOutputAmount,
+1 I didn't realize that `formatEther` could process `bigint` types

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/parseEnv.ts
OOC why was this updated?

2025-01-07 16:10 UTC, james-a-morris commented on packages/indexer/src/utils/currencyUtils.ts
> +}
We have a similar function in the SDK - maybe we should defer to this

2025-01-07 17:32 UTC, daywiss commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  @Column({ type: "decimal" })
sure, im not sure what the difference is but i can change it to float

2025-01-07 17:33 UTC, daywiss commented on packages/error-handling/src/utils/assert.ts
> +): asserts value is NonNullable<unknown> {
after you assert something exists, typscript should be able to infer that its not null, that wasnt happening before

2025-01-07 17:36 UTC, daywiss commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +@Entity()
im not sure i know what this means, looking at the other entities, i dont see them being named here

2025-01-07 17:37 UTC, daywiss commented on packages/indexer-database/src/entities/RelayHashInfo.ts
> +  outputPriceUsd: number;
ill put whatever you think makes sense, im not familiar with the nuances

2025-01-07 17:39 UTC, daywiss commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +      IndexerQueues.PriceQuery, // Use queue name as job name
Im just following the pattern from previous workers, but its passing the queue and then the name of the queue, is based on the enum

2025-01-07 17:40 UTC, daywiss commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +    await this.publishNewRelays(events.filledV3RelayEvents);
i think so

2025-01-07 17:41 UTC, daywiss commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +    await this.publishNewRelays(events.filledV3RelayEvents);
actually i think we want to wait for all sideeffects to complete before trying to run the job

2025-01-07 17:42 UTC, amateima commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  @Column({ type: "decimal" })
Not sure what float is @james-a-morris. These are the Postgres numeric types 
<img width="1060" alt="Screenshot 2025-01-07 at 19 41 41" src="https://github.com/user-attachments/assets/3dbfef2f-b0c4-40ae-bbb2-09a02148c5ce" />

2025-01-07 17:46 UTC, amateima commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +    await this.publishNewRelays(events.filledV3RelayEvents);
I don't think they can be parallelized as we need to wait for deposit and fill events to be associated with relay hashes entites

2025-01-07 17:47 UTC, amateima commented on packages/indexer/src/utils/currencyUtils.ts
> +}
+1 if such function exists

2025-01-07 17:47 UTC, daywiss commented on packages/indexer/src/messaging/priceWorker.ts
> +      normalizedInputAmount - normalizedOutputAmount,
i didnt think about that, but yea looking at the type: `type BigNumberish = BigNumber | Bytes | bigint | string | number;`

2025-01-07 17:49 UTC, daywiss commented on packages/indexer/src/parseEnv.ts
originally there was some env changes made for this pr, which are no longer needed, but this was accidentally left in

2025-01-07 17:50 UTC, daywiss commented on packages/indexer/src/parseEnv.ts
i think stylistically this is slightly better than before but i can revert if you like the other way better

2025-01-07 18:08 UTC, daywiss commented on packages/indexer/package.json
> +    "luxon": "^3.5.0",
basically just using it to get the time formatted to the coingecko call

2025-01-07 18:29 UTC, daywiss commented on packages/indexer/src/utils/currencyUtils.ts
> +}
will need to tackle this when i get back, but was able to remove the coingecko library

2025-01-07 18:43 UTC, james-a-morris commented on packages/indexer-database/src/entities/HistoricPrice.ts
> +  @Column({ type: "decimal" })
Ah maybe I'm thinking of a different RDBMS

2025-01-09 15:14 UTC, james-a-morris reviewed
Curious about https://github.com/across-protocol/indexer/pull/138#discussion_r1905680247

2025-01-13 13:25 UTC, amateima commented
@daywiss I updated the migration files as they should reflect the last version of the DB schema, not all the transformations that the DB suffered during the development

2025-01-13 17:59 UTC, daywiss commented on packages/indexer/src/utils/currencyUtils.ts
> +}
i cant use the one in the sdk unfortunately, it does not return all the data i need from the token. this is what i found:
https://github.com/across-protocol/sdk/blob/master/src/utils/TokenUtils.ts#L112
which omits the coingeckoId.  will keep this in as to not block this pr for now

2025-02-03 16:38 UTC, melisaguevara reviewed
Left some comments.
My main thinking is that we should trigger this worker for each inserted deposit instead of fills. Unless I'm missing something, it looks like we can get all the params we need from the deposit event.
Regarding duplicated deposits, I think we should use some unique key when sending messages to the processor. That way we can be confident we are getting the row we want to process from relayHashInfo. With the current fields (relayHash, originChainId) we can get a different row that also matches this criteria. My proposal is to use depositEventId.

2025-02-03 16:38 UTC, melisaguevara commented on packages/indexer/src/messaging/priceWorker.ts
> +    });
I don't think we need this query as we are already loading the relations in line 174. We should be able to use `relayHashInfo.depositEvent`

2025-02-03 16:38 UTC, melisaguevara commented on packages/indexer/src/messaging/priceWorker.ts
> +    const outputTokenAddress = relayHashInfo.fillEvent.outputToken;
Are there any reasons to get this data from the fill event instead of the deposit? If not, I think we can trigger this worker for each deposit instead of for each fill.

2025-02-03 16:38 UTC, melisaguevara commented on packages/indexer/src/messaging/priceWorker.ts
> +      );
Now there could be multiple deposits matching this criteria, but I think it's still valid to use this params and update them all as all their params will match.

2025-02-03 16:38 UTC, melisaguevara commented on packages/indexer/src/messaging/priceWorker.ts
> +    });
Now there could be many relayHashInfo records matching this criteria. I think if we could trigger this for each inserted deposit and send the deposit event id in the message for this worker, then we should be able to do something like:
```
const relayHashInfo = await this.relayHashInfoRepository.findOne({
      where: { depositEventId },
      relations: {
        depositEvent: true,
      },
    });
```
This would avoid for example getting one row that matches the criteria but doesn't have the deposit associated yet.

2025-02-03 17:18 UTC, amateima commented on packages/indexer/src/messaging/priceWorker.ts
> +    const outputTokenAddress = relayHashInfo.fillEvent.outputToken;
I think it is like this in order to be able to compute the relayer gas fee in the same step

2025-02-03 18:09 UTC, melisaguevara commented on packages/indexer/src/messaging/priceWorker.ts
> +    const outputTokenAddress = relayHashInfo.fillEvent.outputToken;
mmm I see. What about deposits that don't get filled? Do we want to compute those fees?

2025-02-04 14:43 UTC, daywiss commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +      );
i just tried this, but typescript complains since it thinks data can always be undefined even after a check since `SaveQueryResult<entities.FilledV3Relay>` data can be undefined
```
type SaveQueryResult<T> = {
    data: T | undefined;
    result: SaveQueryResultType;
}
```

but im gonna change it anyway and just override typescript

2025-02-04 15:34 UTC, melisaguevara commented on packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
> +  // this has been converted from block time seconds
What does this mean? I don't understand

2025-02-04 15:34 UTC, melisaguevara approved these changes
lgtm! 👍🏼

2025-02-04 17:31 UTC, daywiss commented
@amateima this has been updated for the upcoming changes to deposit ids and rebased against #163

2025-02-04 17:32 UTC, daywiss commented on packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
> +  // this has been converted from block time seconds
not sure, i can remove this

2025-02-04 19:09 UTC, james-a-morris commented on packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
> +  // this has been converted from block time seconds
+1 on removal unless it's needed

2025-02-04 19:09 UTC, james-a-morris commented on packages/indexer-database/src/migrations/1735922359359-RelayHashInfo.ts
Would it make sense to associate this table with the historic price through FK relationships?

2025-02-04 19:09 UTC, james-a-morris commented on packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
> +    await this.publishNewRelays(storedEvents.fills);
This should go above the timing and be included in timings since we're trying to track system time

2025-02-04 19:09 UTC, james-a-morris commented on packages/indexer/src/messaging/priceWorker.ts
> +}
Did we add a timing library to handle this?

2025-02-04 19:09 UTC, james-a-morris commented on packages/indexer/src/messaging/priceWorker.ts
> +    }
Where do we cache this? I don't see it being set later on

2025-02-05 15:17 UTC, daywiss commented on packages/indexer-database/src/migrations/1735922359359-RelayHashInfo.ts
maybe but i dont think its needed. @amateima what do you think?

2025-02-12 13:46 UTC, amateima approved these changes

2025-02-12 13:47 UTC, merged