improve(docker): dockerfiles
across-protocol/indexer pull request #17
Opened 2024-08-26 17:37 UTC by james-a-morris

This reduces the need for multiple docker commands in the package.json and allows for just calling `docker-compose up`

2024-08-26 23:40 UTC, amateima requested changes
<img width="1108" alt="Screenshot 2024-08-27 at 02 37 53" src="https://github.com/user-attachments/assets/f55d9a9b-b4c9-486e-8cee-2ed40d1a4166">

I tried to build the image locally by running `docker build . -t across-indexer-image` and got the error from the screenshot.

Also, I think we need to do some things that are particular for monorepos. Didn't read much of it, but I found [this](https://turbo.build/repo/docs/guides/tools/docker) in the Turborepo docs 👀

2024-08-26 23:40 UTC, amateima commented on docker-compose.yml
> +      - indexer-pgdata:/var/lib/postgresql/data
I like named volumes instead of volumes stored on disk 👍

2024-08-26 23:40 UTC, amateima commented on docker/dev.command.sh
> +pnpm --filter @repo/node-app start
Which app will be started with this command?

2024-08-26 23:40 UTC, amateima commented on docker-compose.yml
> +    command: ["/bin/sh", "./docker/dev.command.sh"]
Both the indexer and the indexer api will run this script resulting in the migration files to be executed twice, so we need to differentiate the commands executed by these 2 services. Different sh files or commands specified directly in the `command` instruction

2024-08-27 14:51 UTC, james-a-morris commented on Dockerfile
> +FROM node:lts-iron AS development
Updated. `lts/iron` is `v20` on the latest minor version btw

2024-08-27 14:52 UTC, james-a-morris commented on docker-compose.yml
> +      - indexer-pgdata:/var/lib/postgresql/data
https://github.com/across-protocol/indexer/pull/17/commits/a3f7c462260bcb515c7f8b74413d8ebc602f0c1b

2024-08-27 14:53 UTC, james-a-morris commented on docker-compose.yml
> +    command: ["/bin/sh", "./docker/dev.command.sh"]
These are differentiated on 
```
environment:
      APP: indexer
```
and 
```
environment:
    APP: indexer-api
```

2024-08-27 15:09 UTC, james-a-morris commented on docker-compose.yml
> +      - indexer-pgdata:/var/lib/postgresql/data
disregard above.

2024-08-27 16:46 UTC, daywiss approved these changes

2024-08-27 18:24 UTC, james-a-morris commented on Dockerfile
> +COPY . .
We no longer need to do this :)

2024-08-29 12:09 UTC, amateima commented on docker/dev.command.sh
> +if [ "$APP" = "indexer-api" ]; then
Here should be the indexer app

2024-08-29 12:09 UTC, amateima commented on docker/prod.command.sh
> +if [ "$APP" = "indexer-api" ]; then
```suggestion
if [ "$APP" = "indexer" ]; then
```

2024-08-29 12:09 UTC, amateima commented on docker/prod.command.sh
> +# Check if the APP ENV is indexer-api
```suggestion
# Check if the APP ENV is indexer
```

2024-08-29 12:09 UTC, amateima commented on docker/prod.command.sh
> +node dist/app.js
Do you think would be a more readable code if we use pnpm commands here?

2024-08-29 12:09 UTC, amateima commented on packages/indexer-api/package.json
> +    ".": "./dist/index.js"
I guess this is related to how we use and import packages, but what's more exactly the impact of this change?

2024-08-29 13:57 UTC, melisaguevara reviewed
Should we add the ENV requirements and the run/build commands to the README?

2024-08-29 14:03 UTC, melisaguevara commented on docker/dev.command.sh
> +if [ "$APP" = "indexer-api" ]; then
@amateima do you see any issues if we delete this condition?
I think it's ok that we try to run migrations when running any of the apps. If migrations were already executed the command will do nothing.

2024-08-29 14:04 UTC, james-a-morris commented on Dockerfile
> +CMD ["sh", "./docker/prod.command.sh"]
https://github.com/across-protocol/indexer/pull/17/commits/57b5c9989d94a5d88b370feb4a59321b294e7ebf

2024-08-29 14:07 UTC, james-a-morris commented on .dockerignore
> +**/dist
We could - but the Dockerfile should only be migrating source code.

2024-08-29 14:15 UTC, james-a-morris commented on .dockerignore
> +**/dist
makes sense +1 - https://github.com/across-protocol/indexer/pull/17/commits/3eeac46df68e98572b2bae5c3c6a86c1c3e198e9

2024-08-29 14:16 UTC, james-a-morris commented on packages/indexer-api/package.json
> +    ".": "./dist/index.js"
cc @melisaguevara & @daywiss  - I couldn't find any major issues when testing but is there special consideration that should be made?

2024-08-29 15:38 UTC, james-a-morris commented on docker/dev.command.sh
> +if [ "$APP" = "indexer-api" ]; then
I am thinking about this a bit more. It would make sense to document this better & use a separate ENV var to reference any migrations - this way, we can avoid enforcing running the migrations on specific app names.

2024-08-29 15:39 UTC, james-a-morris commented on docker/prod.command.sh
> +# Check if the APP ENV is indexer-api
https://github.com/across-protocol/indexer/pull/17#discussion_r1736523541

2024-08-29 15:39 UTC, james-a-morris commented on docker/prod.command.sh
> +if [ "$APP" = "indexer-api" ]; then
https://github.com/across-protocol/indexer/pull/17#discussion_r1736523541

2024-08-29 15:39 UTC, james-a-morris commented on packages/indexer-api/package.json
> +    ".": "./dist/index.js"
synced offline - @amateima

2024-08-30 12:04 UTC, melisaguevara approved these changes

2024-09-02 12:31 UTC, amateima commented on docker/dev.command.sh
> +if [ "$APP" = "indexer-api" ]; then
> @amateima do you see any issues if we delete this condition? I think it's ok that we try to run migrations when running any of the apps. If migrations were already executed the command will do nothing.

I think the issue is if the migrations are executed in the same time. One set of migrations are going to fail

2024-09-02 12:32 UTC, amateima commented on docker/dev.command.sh
> +if [ "$APP" = "indexer-api" ]; then
> I am thinking about this a bit more. It would make sense to document this better & use a separate ENV var to reference any migrations - this way, we can avoid enforcing running the migrations on specific app names.

Yeah, we'll discuss this when you are back 👍

2024-09-04 01:40 UTC, amateima approved these changes

2024-09-04 04:34 UTC, merged