feat: add more robust block range update tracking
across-protocol/indexer pull request #23
Opened 2024-09-05 17:57 UTC by daywiss

## motivation
We want a more robust way to track what block ranges we have sucessfully queried. 

## changes
This changes how we do this by instantiating a single spoke pool client along with its own hub/config store clients, it will now attempt small ranges of blocks and save the result to redis ( success/failure) that way we can either retry or avoid reprocessing block ranges.  This currently only stores spoke pool events.

2024-09-05 18:02 UTC, daywiss commented on packages/indexer/src/services/commands.ts
> +export class CommandStore {
this class is basically just meant to store block ranges that we are either: processing, sucessfully processed, or had an error

2024-09-05 18:03 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +export function Indexer(config: Config) {
this service has a lot in common with the original deposit indexer service, lots of code copied and pasted here, eventually this would replace that service, since we have the ability to monitor which block ranges we have successfully stored

2024-09-05 18:03 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  async function tick() {
this is the main logical function, should automatically update ranges, store events and possibily repair broken queries ( not implemented )

2024-09-05 18:05 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  async function updateUnprocessedRanges(toBlock?: number) {
this funciton is still a WIP, but the idea is that we have a collection of block ranges that have succeeded, failed, or are in progress.  This should compare that to the latest block, and determine what ranges we need to queue up to process,

2024-09-05 18:05 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  async function fetchEventsByRange(fromBlock: number, toBlock: number) {
This is the main event fetching logic, initializes all clients, updates them then returns relevent events we want to store

2024-09-05 18:06 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  async function storeEvents(params: {
takes a map of all the events and stores them in postgres

2024-09-05 18:06 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  async function addRange(fromBlock: number, toBlock: number) {
helper function that lets us persist a range query to redis, will error if we are saving one we have already enqueued.  does not check error/completed range queries.

2024-09-05 18:09 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  const pendingCommands = new commands.CommandStore({
these "commands" just represent block range queries in a certain state: pending, resolved, rejected.
right now we manually just delete and set ranges between each of these tables, not acid compliant, but its ok for a proof of concept. would only really fail if we ended the app right between a delete and set, or if one or the other fails

2024-09-05 18:10 UTC, daywiss commented on packages/indexer/src/services/indexer.ts
> +  const spokePoolProvider = getRetryProvider({
note we only intanciate a single spoke pool for this service, we will need one service for each spoke pool we want to index

2024-09-05 19:51 UTC, melisaguevara commented on packages/indexer/src/services/commands.ts
> +    assert(isCommandBase(cmd), "Command already has result or error");
should this check if command is CommandError or CommandResult instead of CommandBase?

2024-09-06 17:53 UTC, daywiss commented on packages/indexer/src/services/commands.ts
> +    assert(isCommandBase(cmd), "Command already has result or error");
removed this function for now!

2024-09-09 16:15 UTC, melisaguevara commented on packages/indexer/src/services/spokePoolEvents.ts
> +export async function SpokePoolEvents(config: Config) {
Would it make sense to turn this into a class? Or do you think it's better to keep this as a function?

2024-09-09 18:06 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +}
yes, let me save that for future pr when i add that feature!

2024-09-10 15:48 UTC, melisaguevara approved these changes
lgtm!

2024-09-10 16:01 UTC, james-a-morris commented on packages/indexer/src/services/spokePoolEvents.ts
> +export async function SpokePoolEvents(config: Config) {
I'm not sure I follow. It looks like we can have a constructor reference the initialization logic (216-259), scope the `tick` function as public, and make the rest private.

2024-09-10 17:06 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +export async function SpokePoolEvents(config: Config) {
there is an async call to fetch the top level hub and config clients: https://github.com/across-protocol/indexer/pull/23/files#diff-7b1a9cecc479c0cbfba7d248647a84a648625851bc26ef915a6c821b9f507631R253
which cannot be included in a constructor.   this could be moved to a secondary async initialization funciton, or do some kind of singleton init in the tick function, but that seemed overly complex.  but im happy to massage this into a class if that is what people prefer!

2024-09-10 17:41 UTC, daywiss commented on pnpm-lock.yaml
i dug into this. turns out master has a bad lockfile installed, when i installed lodash this triggered pnpm to repair the file and that is the source of all the changes. not sure how we can avoid this in the future

2024-09-10 17:42 UTC, daywiss commented on pnpm-lock.yaml
if you checkout master, run `pnpm install` in root, im seeing this error: `WARN  Ignoring broken lockfile at /home/dev/src/risklabs/indexer: Lockfile /home/dev/src/risklabs/indexer/pnpm-lock.yaml`. see if you get something similar

2024-09-10 17:43 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +}
i made this change in the hubpool event indexer pr coming up next

2024-09-10 17:49 UTC, daywiss commented on packages/indexer/src/main.ts
> +  // });
i can just remove this for now and prefer the code in this pr for now. will fast follow with rest of features

2024-09-10 17:54 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +  const fromBlock = params.fromBlock ?? deployedBlockNumber;
redis is used to manage block ranges external to the client, see here where we fetch known completed ranges: https://github.com/across-protocol/indexer/pull/23/files#diff-7b1a9cecc479c0cbfba7d248647a84a648625851bc26ef915a6c821b9f507631R310

2024-09-10 17:55 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +  );
i can give it a shot

2024-09-10 18:00 UTC, daywiss commented on packages/indexer/src/rangeQueryStore.ts
> +export class RangeQueryStore {
not sure what you mean, theres a few private functions there, the rest should be public

2024-09-10 18:09 UTC, daywiss commented on packages/indexer/src/main.ts
> +          maxBlockLookBack: 10000,
is there a way to include specific look back per chain, or are you saying i should copy them into a constants file?

2024-09-10 18:09 UTC, daywiss commented on packages/indexer/src/main.ts
> +      };
i can try to clean it up a bit

2024-09-10 22:13 UTC, amateima commented on packages/indexer/src/services/spokePoolEvents.ts
> +  async function getUnprocessedRanges(toBlock?: number): Promise<Ranges> {
This function assumes that `blockLookBack` is the same during different launches of the indexer, right? If I start the indexer with a lookback of 10k, stop it, and then restarted with a lookback 100k, all the blocks will be processed again

2024-09-10 22:13 UTC, amateima commented on packages/indexer/src/main.ts
> +      await spokeIndexer.tick();
Can we add polling logic here? Query events every x seconds. This is how the indexer is supposed to run

2024-09-11 11:03 UTC, daywiss commented on packages/indexer/src/main.ts
> +  if (postgres && redis && retryProviderConfig) {
previously these were optional, we can just make them required at this point

2024-09-11 14:31 UTC, daywiss commented on packages/indexer/src/rangeQueryStore.ts
> +    assert(!(await this.has(id)), "Range already exists");
removing unused functions

2024-09-11 14:32 UTC, daywiss commented on packages/indexer/src/rangeQueryStore.ts
> +  }
yes will remove unused functions

2024-09-11 16:27 UTC, daywiss commented on packages/indexer/src/rangeQueryStore.ts
> +import assert from "assert";
goign to move this to a redis folder since database implies postgres classes

2024-09-11 16:32 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +export async function SpokePoolEvents(config: Config) {
will rename this accordingly

2024-09-11 16:35 UTC, daywiss commented on packages/indexer/src/services/spokePoolEvents.ts
> +  async function getUnprocessedRanges(toBlock?: number): Promise<Ranges> {
yea good point, it does use block range pairs, so changes to the lookback will cause it to miss and rerun

2024-09-11 17:08 UTC, amateima commented on packages/indexer/src/services/spokePoolEvents.ts
> +export async function SpokePoolEvents(config: Config) {
For me it's ok to stick with this implementation

2024-09-11 17:22 UTC, amateima requested changes

2024-09-11 17:22 UTC, amateima commented on packages/indexer/src/main.ts
> +  } while (!exitRequested);
Doing the polling logic here breaks the decoupling between the spoke pool clients as all clients need to finish in order to move to the next block range. The clients will need different polling intervals depending on the block time. 
I think the polling logic should be part of the `SpokePoolIndexer` as the main.ts entrypoint would not have to deal with such an implementation detail 

```
SpokePoolIndexer {
  start() {
    looping logic {
      tick()
    }
  }
  
  tick() { ... }
}

spokeIndexer.start()
```

2024-09-11 18:34 UTC, daywiss commented on packages/indexer/src/main.ts
> +  } while (!exitRequested);
updated this

2024-09-11 19:59 UTC, james-a-morris commented on packages/indexer/src/rangeQueryStore.ts
I'm of two minds here. I think JSDoc is a low-lift that goes a long way toward maintainability - and it's more convenient to write them when the code is fresh. 

It will also increase overall code readability for external projects that look at this repo to understand what is happening under the hood.

2024-09-11 20:00 UTC, james-a-morris commented on packages/indexer/src/rangeQueryStore.ts
> +export class RangeQueryStore {
I.e. `public`/`private` when declaring functions.

2024-09-11 21:05 UTC, amateima approved these changes

2024-09-12 07:54 UTC, daywiss commented on packages/indexer/src/main.ts
> +          maxBlockLookBack: 10000,
i see, ok yes i still have an issue to refactor configs, so if you dont mind id like to do it in that pr

2024-09-12 07:55 UTC, daywiss commented on packages/indexer/src/rangeQueryStore.ts
> +export class RangeQueryStore {
explicitly declaring public vs just using the default scope? yea im ok with either way, i can explicitly declare it

2024-09-12 13:46 UTC, merged