feat: spokePoolProcessor
across-protocol/indexer pull request #37
Opened 2024-09-17 15:22 UTC by melisaguevara

This PR includes a new processor for SpokePool events. It runs after every update of a spoke pool client and:
- Updates relayHashInfo table based on new events.
- Updates the status of relayHashInfo rows based on the associated events.
- Tries to identify refunds for expired deposits based on ExecutedRelayerRefundRoot events.

2024-09-18 14:05 UTC, amateima requested changes

2024-09-18 14:05 UTC, amateima commented on packages/indexer/src/services/spokePoolProcessor.ts
> +      .getMany();
instead of joining tables having millions of rows, can we work only with the events returned by the contract clients by passing them as a parameter? I think we might want to limit this process step to only the events returned by the `update()` function. We can discuss this individually for each function out of `assignSpokeEventsToRelayHashInfo`, `updateRelayStatus`, `updateRefundedDepositsStatus`

2024-09-18 19:17 UTC, melisaguevara commented on packages/indexer/src/services/spokePoolProcessor.ts
> +      .getMany();
I think we could use that approach for updating `relayHashInfo` event rows and potentially for refunds too.
Using it also for `updateRelayStatus` will make us lose track of expired deposits.
One question I have is related to error handling, if any of those steps throws, should we let the indexer break? or should we somehow track the failed updates to retry them later?

2024-09-20 15:55 UTC, amateima approved these changes

2024-09-20 19:28 UTC, merged